HD_COMPONENT_NAME	= Xspec

HD_COMPONENT_VERS	= 

HD_LIBRARY_ROOT		= XSFunctions

HD_LIBRARY_SRC_cxx	= acisabs.cxx agauss.cxx apec.cxx Aped.cxx \
			  bapec.cxx brokenPowerLaw.cxx \
			  broken2PowerLaw.cxx brnei.cxx btapec.cxx bvapec.cxx bvrnei.cxx \
			  bvtapec.cxx bvvapec.cxx bvvrnei.cxx bvvtapec.cxx \
			  c6mekl.cxx c6pmekl.cxx c6pvmkl.cxx c6vmekl.cxx \
			  calc_xscat.cxx calcCoolingFlow.cxx calcLines.cxx \
			  calcMultiTempPlasma.cxx carbatm.cxx cph.cxx cplinear.cxx \
			  cutoffPowerLaw.cxx functionMap.cxx PartialCovering.cxx \
			  powerLaw.cxx simpl.cxx trns.cxx funcWrappers.cxx \
			  r1mach.cxx cemVMekal.cxx cflux.cxx clumin.cxx \
			  clcmek.cxx continua.cxx cpflux.cxx \
			  diskline.cxx \
			  equil.cxx \
			  gaussianLine.cxx gaussianAbsorptionLine.cxx \
			  gaussDem.cxx gsmooth.cxx gnei.cxx \
			  hatm.cxx \
			  IonBalNei.cxx IonizedOpacity.cxx ireflct.cxx \
			  KBcalcNEISpectrum.cxx kdblur.cxx kdblur2.cxx \
			  kerrbb.cxx kerrd.cxx \
			  laor.cxx laor2.cxx log10con.cxx logconst.cxx \
			  logpar.cxx lorentzianLine.cxx lsmooth.cxx \
			  meka.cxx mekal.cxx MZCompRefl.cxx \
			  nei.cxx NeutralOpacity.cxx \
			  nlapec.cxx npshock.cxx nsmax.cxx nsmaxg.cxx nsx.cxx nthcomp.cxx \
			  pileup.cxx pshock.cxx raysmith.cxx rdblur.cxx rnei.cxx \
			  reflct.cxx rfxconv.cxx sedov.cxx sirf.cxx snapec.cxx \
			  spinconv.cxx spin.cxx sumdem.cxx superExpCutoff.cxx swind1.cxx \
			  tableInterpolate.cxx tapec.cxx tbabs.cxx tbfeo.cxx \
			  tbgas.cxx tbgrain.cxx tbpcf.cxx tbrel.cxx tbvabs.cxx \
			  vapec.cxx vashift.cxx vcph.cxx vgaussDem.cxx vequil.cxx \
			  vmeka.cxx vmekal.cxx vgnei.cxx vmshift.cxx vnei.cxx \
			  vnpshock.cxx voigtLine.cxx vraysmith.cxx vpshock.cxx \
			  vrnei.cxx vsedov.cxx vtapec.cxx vvapec.cxx vvgnei.cxx \
			  vvnei.cxx vvnpshock.cxx vvpshock.cxx vvrnei.cxx \
			  vvsedov.cxx vvtapec.cxx \
			  WarmAbsorber.cxx xilconv.cxx xsbexrav.cxx \
			  xsbexriv.cxx xscat_init.cxx xscatmodel.cxx xscflw.cxx \
			  xscompps.cxx xscompth.cxx \
			  xseqpair.cxx xseqth.cxx \
			  xsmaug.cxx xsmkcf.cxx \
			  xsnteea.cxx xspexrav.cxx xspexriv.cxx xspwab.cxx \
			  xsvmcf.cxx xszgau.cxx zagauss.cxx zashift.cxx \
			  zkerrbb.cxx zmshift.cxx ztbabs.cxx zxipcf.cxx \
			  Utilities/ComponentInfo.cxx Utilities/FunctionUtility.cxx \
			  Utilities/MdefExpression.cxx Utilities/XSCCall.cxx \
			  Utilities/XSF77.cxx Utilities/XSModelFunction.cxx \
			  Utilities/xsFortran.cxx

HD_LIBRARY_SRC_c	= exsource.c ismatten.c rgsxsrc.c tbnew.c xsgrbcomp.c \
			  xscompmag.c xscomptb.c numeric.c xslimbb.c xszbabs.c bwcycl.c 

HD_LIBRARY_SRC_f	= agnsed.f agnslim.f atdata.f bbm.f cemekl.f \
			  compbb.f compls.f compps.f compst.f cont.f \
			  disk.f diskir.f diskm.f disko.f diskpbb.f \
			  donthcomp.f dopwab.f dospin.f dotbvabs.f \
			  eplogpar.f eqpairsubs.f erebin.f ezdiskbb.f \
			  fespecs.f fmekal.f gaunt.f gphoto.f grad.f \
			  inibin.f jet.f kummr.f \
			  idre.f kyconv.f kyrline.f \
			  meksub.f msldst.f mszdst.f \
			  nei1tspec.f nsa.f nsagrav.f nsatmos.f \
			  optxagn.f optxagnf.f pexmon.f phfit2.f photo.f \
			  qsosed.f runkbb.f \
			  srcut.f sresc.f ssa.f tamma.f \
			  xredge.f xsabsc.f xsabsp.f xsabsv.f xsabsw.f \
			  xsbbrd.f xsblbd.f xsbmc.f xsbrms.f xsbrmv.f \
			  xscabs.f xscnst.f xscred.f xscycl.f \
			  xsdiskpn.f xsdskb.f xsdust.f xsedge.f \
			  xsexp.f xsgaul.f xsgrbm.f xshecu.f xshrfl.f \
			  xslorz.f xslyman.f xsntch.f xsnteeasb.f xsp1tr.f \
			  xspegp.f xsphab.f xsphei.f xsplab.f xsposm.f \
			  xsred.f xsrefsch.f xssmdg.f xsspln.f xssssi.f \
			  xsstep.f xstitg.f xsvphb.f xswnab.f \
			  xsxirf.f xsxpdec.f xszabp.f xszabs.f xszbod.f \
			  xszbrm.f xszcrd.f xszedg.f xszhcu.f xszphb.f \
			  xszvab.f xszvfe.f xszvph.f xszwnb.f zigm.f

HD_LIBRARY_SRC_f90	= ismabs.f90 ismdust.f90 olivineabs.f90 th.f90

HD_CXXFLAGS		= -I${HD_SRC}/src \
			  -I${HD_SRC}/src/main -I${HD_SRC}/src/include \
			  -I${HD_SRC}/src/XSFunctions \
			  -I${HD_SRC}/src/XSFunctions/Utilities \
			  -I${HD_SRC}/src/xslib \
			  -I${HD_SRC}/src/XSUtil ${HD_STD_CXXFLAGS} \
			  -DINXSPEC

HD_CFLAGS               = -I${HD_SRC}/src \
			  -I${HD_SRC}/src/main -I${HD_SRC}/src/include \
			  -I${HD_SRC}/src/XSUtil ${HD_STD_CFLAGS}

HD_FFLAGS		= -I${HD_SRC}/src \
			  -I${HD_SRC}/src/main -I${HD_SRC}/src/include \
			  -I${HD_SRC}/src/XSFunctions \
			  -I${HD_SRC}/src/xslib \
			  -I${HD_SRC}/src/XSUtil ${HD_STD_FFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

HD_INSTALL_HEADERS	= Aped.h IonBalNei.h IonizedOpacity.h MZCompRefl.h \
			  NeutralOpacity.h \
			  exsource.h fephoto.h nephoto.h numeric.h \
			  ophoto.h trns.h stlToCArrays.h \
			  xscat.h xslimbb.h \
			  functionMap.h funcWrappers.h \
			  Utilities/ComponentInfo.h Utilities/FunctionUtility.h \
			  Utilities/MdefExpression.h Utilities/XSModelFunction.h \
			  Utilities/funcType.h Utilities/xsFortran.h bwcycl.h
			  

HD_CLEAN		= ${HD_LIBRARY_SRC_cxx:.cxx=.o} \
			  ${HD_LIBRARY_SRC_c:.c=.o} \
			  ${HD_LIBRARY_SRC_f:.f=.o}

HD_SHLIB_LIBS		= ${HD_LFLAGS} -lXSUtil -lXS -l${WCSLIB} -l${HEASP} \
			  -l${HEAUTILS} -l${FFTW} -l${FGSL} ${GSL_LIBS} \
			  -l${CCFITS} -l${CFITSIO} ${SYSLIBS} ${F77LIBS4C}

include ${HD_STD_MAKEFILE}
